### ISSUE TITLE
Compiled and loads OK, but I still get "color_coded unavailable: you need to compile it"

### ISSUE THREAD

**Issue by captcha1** [jeaye/color_coded#29]
I tried to compile on Fedora 21.  I got some error messages:

include/clang/token.hpp:62:16: error: ‘CXType_IncompleteArray’ was not declared in this scope

... so I used the Fedora package clang-devel-3.5.0-6.fc21.i686

Then it compiled OK, but I still get "color_coded unavailable: you need to compile it"

I did an "strace" on vim, and it loads OK:

open("/home/user/.vim/bin/color_coded.so", O_RDONLY|O_CLOEXEC) = 4

... then loads the dependent libraries (libz, libcurses, libstdc++ , libgcc_s), but then issues the error message: "color_coded unavailable: you need to compile it".

For some reason "pcall" returns "not loaded", and I don't know why.

**Comment by jeaye** [comment]
> open("/home/user/.vim/bin/color_coded.so", O_RDONLY|O_CLOEXEC) = 4

This is all sorts of wrong. If anything it should be `/home/user/.vim/bundle/color_coded/bin`. Did you extract color_coded directly into your `/home/user/.vim` directory?

An easy way to test if lua can load color_coded is to hop into the `bin` directory (containing `color_coded.so`) and run:
```bash
lua -l color_coded
```
If this brings you into a lua prompt without showing any errors, you're good. If there are errors, please paste them here. Aside from that, would you mind deleting your color_coded directory and going through the whole process again, but this time paste the entire session here so I can see the output of each command?

Next, you mentioned that you needed to change your compiler on Fedora in order for this to work. As the README says, this should work with GCC 4.9 and/or clang 3.4. Which compiler did you have before upgrading? Would you mind telling me the upgrade steps so I can include them in the README under Fedora?

**Comment by jeaye** [comment]
One last thing, if you're not building from the `cmake` branch, give that a shot. color_coded is in the middle of a migration to the cmake build system and it offers a lot more portability than what there is currently. When you give the build output, please do so with the cmake branch, since that's what'll give us the best results. Thanks for helping.

**Comment by captcha1** [comment]
lua -l color_coded
lua: error loading module 'color_coded' from file './color_coded.so':
        ./color_coded.so: undefined symbol: clang_getTokenSpellin

I'll post the full session soon.

**Comment by jeaye** [comment]
Please try again with the latest master, @captcha1.

**Comment by jeaye** [comment]
Also, @captcha1 make sure you not only `make` but also `make install`. Check the README for the instructions.

**Comment by jeaye** [comment]
I'm closing this. If you have an issue with the new build system, please either reopen this or make a new ticket for that issue.

**Comment by svloyso** [comment]
Hello. 
I faced the same problem: compilation of color_coded was successfull (with gcc 6.1) and plugin works properly, but annoying message "color_coded unavailable: you need to compile it" appears in every vim launch. 

When i run 
`lua -l color_coded`
from directory with color_coded.so, i get this error message:
```
lua: error loading module 'color_coded' from file './color_coded.so':
	libclang.so.3.8: cannot open shared object file: No such file or directory
stack traceback:
	[C]: in ?
	[C]: in function '_G.require'
	[C]: in ?
```
